apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msal-app-ingress
spec:
  rules:
  - host: msal.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: msal-app-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: msal-api-service
            port:
              number: 80
